// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

// Protobuf Java Version: 3.25.6
package ly.proto;

public final class Cmd {
  private Cmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 注意 双号是上行包，单号是下行包
   * </pre>
   *
   * Protobuf enum {@code CMD}
   */
  public enum CMD
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CMD_null = 0;</code>
     */
    CMD_null(0),
    /**
     * <pre>
     *登录协议请求
     * </pre>
     *
     * <code>CS_Login = 101;</code>
     */
    CS_Login(101),
    /**
     * <pre>
     *登录协议响应
     * </pre>
     *
     * <code>SC_Login = 102;</code>
     */
    SC_Login(102),
    /**
     * <pre>
     *退出协议请求
     * </pre>
     *
     * <code>CS_Logout = 103;</code>
     */
    CS_Logout(103),
    /**
     * <pre>
     *退出协议响应
     * </pre>
     *
     * <code>SC_Logout = 104;</code>
     */
    SC_Logout(104),
    /**
     * <pre>
     *错误码协议请求
     * </pre>
     *
     * <code>CS_ErrorCode = 201;</code>
     */
    CS_ErrorCode(201),
    /**
     * <pre>
     *错误码协议响应
     * </pre>
     *
     * <code>SC_ErrorCode = 202;</code>
     */
    SC_ErrorCode(202),
    /**
     * <pre>
     *&#47;/////////////////////////////msgId 10000 -- 20000 之间的是server之间的消息号，客户端不占用///////////////////////////////////////
     * </pre>
     *
     * <code>CS_Server2Server = 10001;</code>
     */
    CS_Server2Server(10001),
    /**
     * <pre>
     *server2server 服务器之间通信的消息号 响应
     * </pre>
     *
     * <code>SC_Server2Server = 10002;</code>
     */
    SC_Server2Server(10002),
    /**
     * <pre>
     *rpcPing 心跳包 请求
     * </pre>
     *
     * <code>CS_RpcPing = 10003;</code>
     */
    CS_RpcPing(10003),
    /**
     * <pre>
     *rpcPing 心跳包响应
     * </pre>
     *
     * <code>SC_RpcPing = 10004;</code>
     */
    SC_RpcPing(10004),
    /**
     * <pre>
     * 网关调用游戏服务器Rpc方法 请求
     * </pre>
     *
     * <code>CS_Gate2GameRpcGameCall = 10005;</code>
     */
    CS_Gate2GameRpcGameCall(10005),
    /**
     * <pre>
     * 网关调用游戏服务器Rpc方法 响应
     * </pre>
     *
     * <code>SC_Gate2GameRpcGameCall = 10006;</code>
     */
    SC_Gate2GameRpcGameCall(10006),
    /**
     * <pre>
     *maxServeMsgId 服务器之间通信消息号最大值
     * </pre>
     *
     * <code>MaxServeMsgId = 20000;</code>
     */
    MaxServeMsgId(20000),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CMD_null = 0;</code>
     */
    public static final int CMD_null_VALUE = 0;
    /**
     * <pre>
     *登录协议请求
     * </pre>
     *
     * <code>CS_Login = 101;</code>
     */
    public static final int CS_Login_VALUE = 101;
    /**
     * <pre>
     *登录协议响应
     * </pre>
     *
     * <code>SC_Login = 102;</code>
     */
    public static final int SC_Login_VALUE = 102;
    /**
     * <pre>
     *退出协议请求
     * </pre>
     *
     * <code>CS_Logout = 103;</code>
     */
    public static final int CS_Logout_VALUE = 103;
    /**
     * <pre>
     *退出协议响应
     * </pre>
     *
     * <code>SC_Logout = 104;</code>
     */
    public static final int SC_Logout_VALUE = 104;
    /**
     * <pre>
     *错误码协议请求
     * </pre>
     *
     * <code>CS_ErrorCode = 201;</code>
     */
    public static final int CS_ErrorCode_VALUE = 201;
    /**
     * <pre>
     *错误码协议响应
     * </pre>
     *
     * <code>SC_ErrorCode = 202;</code>
     */
    public static final int SC_ErrorCode_VALUE = 202;
    /**
     * <pre>
     *&#47;/////////////////////////////msgId 10000 -- 20000 之间的是server之间的消息号，客户端不占用///////////////////////////////////////
     * </pre>
     *
     * <code>CS_Server2Server = 10001;</code>
     */
    public static final int CS_Server2Server_VALUE = 10001;
    /**
     * <pre>
     *server2server 服务器之间通信的消息号 响应
     * </pre>
     *
     * <code>SC_Server2Server = 10002;</code>
     */
    public static final int SC_Server2Server_VALUE = 10002;
    /**
     * <pre>
     *rpcPing 心跳包 请求
     * </pre>
     *
     * <code>CS_RpcPing = 10003;</code>
     */
    public static final int CS_RpcPing_VALUE = 10003;
    /**
     * <pre>
     *rpcPing 心跳包响应
     * </pre>
     *
     * <code>SC_RpcPing = 10004;</code>
     */
    public static final int SC_RpcPing_VALUE = 10004;
    /**
     * <pre>
     * 网关调用游戏服务器Rpc方法 请求
     * </pre>
     *
     * <code>CS_Gate2GameRpcGameCall = 10005;</code>
     */
    public static final int CS_Gate2GameRpcGameCall_VALUE = 10005;
    /**
     * <pre>
     * 网关调用游戏服务器Rpc方法 响应
     * </pre>
     *
     * <code>SC_Gate2GameRpcGameCall = 10006;</code>
     */
    public static final int SC_Gate2GameRpcGameCall_VALUE = 10006;
    /**
     * <pre>
     *maxServeMsgId 服务器之间通信消息号最大值
     * </pre>
     *
     * <code>MaxServeMsgId = 20000;</code>
     */
    public static final int MaxServeMsgId_VALUE = 20000;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CMD valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CMD forNumber(int value) {
      switch (value) {
        case 0: return CMD_null;
        case 101: return CS_Login;
        case 102: return SC_Login;
        case 103: return CS_Logout;
        case 104: return SC_Logout;
        case 201: return CS_ErrorCode;
        case 202: return SC_ErrorCode;
        case 10001: return CS_Server2Server;
        case 10002: return SC_Server2Server;
        case 10003: return CS_RpcPing;
        case 10004: return SC_RpcPing;
        case 10005: return CS_Gate2GameRpcGameCall;
        case 10006: return SC_Gate2GameRpcGameCall;
        case 20000: return MaxServeMsgId;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CMD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CMD> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CMD>() {
            public CMD findValueByNumber(int number) {
              return CMD.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ly.proto.Cmd.getDescriptor().getEnumTypes().get(0);
    }

    private static final CMD[] VALUES = values();

    public static CMD valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CMD(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CMD)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCmd.proto*\224\002\n\003CMD\022\014\n\010CMD_null\020\000\022\014\n\010CS_" +
      "Login\020e\022\014\n\010SC_Login\020f\022\r\n\tCS_Logout\020g\022\r\n\t" +
      "SC_Logout\020h\022\021\n\014CS_ErrorCode\020\311\001\022\021\n\014SC_Err" +
      "orCode\020\312\001\022\025\n\020CS_Server2Server\020\221N\022\025\n\020SC_S" +
      "erver2Server\020\222N\022\017\n\nCS_RpcPing\020\223N\022\017\n\nSC_R" +
      "pcPing\020\224N\022\034\n\027CS_Gate2GameRpcGameCall\020\225N\022" +
      "\034\n\027SC_Gate2GameRpcGameCall\020\226N\022\023\n\rMaxServ" +
      "eMsgId\020\240\234\001B\n\n\010ly.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
