// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorMsg.proto

// Protobuf Java Version: 3.25.6
package ly.proto;

public final class ErrorMsg {
  private ErrorMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>Ok = 0;</code>
     */
    Ok(0),
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>FAILED = 1;</code>
     */
    FAILED(1),
    /**
     * <pre>
     *系统错误
     * </pre>
     *
     * <code>SYSTEM_ERROR = 2;</code>
     */
    SYSTEM_ERROR(2),
    /**
     * <pre>
     *参数错误
     * </pre>
     *
     * <code>PARAM_ERROR = 3;</code>
     */
    PARAM_ERROR(3),
    /**
     * <pre>
     *账号错误
     * </pre>
     *
     * <code>ACCOUNT_ERROR = 4;</code>
     */
    ACCOUNT_ERROR(4),
    /**
     * <pre>
     *密码错误
     * </pre>
     *
     * <code>PASSWORD_ERROR = 5;</code>
     */
    PASSWORD_ERROR(5),
    /**
     * <pre>
     *账号被禁用
     * </pre>
     *
     * <code>ACCOUNT_FORBIDDEN = 6;</code>
     */
    ACCOUNT_FORBIDDEN(6),
    /**
     * <pre>
     *账号已登录
     * </pre>
     *
     * <code>ACCOUNT_ONLINE = 7;</code>
     */
    ACCOUNT_ONLINE(7),
    /**
     * <pre>
     *账号未注册
     * </pre>
     *
     * <code>ACCOUNT_NOT_REGISTER = 8;</code>
     */
    ACCOUNT_NOT_REGISTER(8),
    /**
     * <pre>
     *玩家名已存在
     * </pre>
     *
     * <code>PLAYER_NAME_EXISTS = 9;</code>
     */
    PLAYER_NAME_EXISTS(9),
    /**
     * <pre>
     *token错误
     * </pre>
     *
     * <code>TOKEN_ERROR = 10;</code>
     */
    TOKEN_ERROR(10),
    /**
     * <pre>
     *玩家不存在
     * </pre>
     *
     * <code>PLAYER_NOT_EXIST = 11;</code>
     */
    PLAYER_NOT_EXIST(11),
    /**
     * <pre>
     * 英雄相关错误码 5000-5099
     * </pre>
     *
     * <code>HERO_NOT_FOUND = 5001;</code>
     */
    HERO_NOT_FOUND(5001),
    /**
     * <pre>
     *英雄不属于当前玩家
     * </pre>
     *
     * <code>HERO_NOT_BELONG = 5002;</code>
     */
    HERO_NOT_BELONG(5002),
    /**
     * <pre>
     *资源不足
     * </pre>
     *
     * <code>RESOURCE_NOT_ENOUGH = 5003;</code>
     */
    RESOURCE_NOT_ENOUGH(5003),
    /**
     * <pre>
     *等级已达上限
     * </pre>
     *
     * <code>LEVEL_MAX = 5004;</code>
     */
    LEVEL_MAX(5004),
    /**
     * <pre>
     *星级已达上限
     * </pre>
     *
     * <code>STAR_MAX = 5005;</code>
     */
    STAR_MAX(5005),
    /**
     * <pre>
     *觉醒已达上限
     * </pre>
     *
     * <code>AWAKEN_MAX = 5006;</code>
     */
    AWAKEN_MAX(5006),
    /**
     * <pre>
     *升星条件不满足
     * </pre>
     *
     * <code>STAR_CONDITION_NOT_MET = 5007;</code>
     */
    STAR_CONDITION_NOT_MET(5007),
    /**
     * <pre>
     *觉醒条件不满足
     * </pre>
     *
     * <code>AWAKEN_CONDITION_NOT_MET = 5008;</code>
     */
    AWAKEN_CONDITION_NOT_MET(5008),
    /**
     * <pre>
     *英雄槽位已满
     * </pre>
     *
     * <code>HERO_SLOT_FULL = 5009;</code>
     */
    HERO_SLOT_FULL(5009),
    /**
     * <pre>
     *英雄已存在
     * </pre>
     *
     * <code>HERO_ALREADY_EXISTS = 5010;</code>
     */
    HERO_ALREADY_EXISTS(5010),
    /**
     * <pre>
     * 场景相关错误码 6000-6099
     * </pre>
     *
     * <code>SCENE_NOT_FOUND = 6001;</code>
     */
    SCENE_NOT_FOUND(6001),
    /**
     * <pre>
     *场景坐标越界
     * </pre>
     *
     * <code>SCENE_OUT_OF_BOUNDS = 6002;</code>
     */
    SCENE_OUT_OF_BOUNDS(6002),
    /**
     * <pre>
     *场景尚未完成启动或恢复
     * </pre>
     *
     * <code>SCENE_NOT_READY = 6003;</code>
     */
    SCENE_NOT_READY(6003),
    /**
     * <pre>
     *当前阶段不支持该场景操作
     * </pre>
     *
     * <code>SCENE_UNSUPPORTED = 6004;</code>
     */
    SCENE_UNSUPPORTED(6004),
    /**
     * <pre>
     *地形阻挡或约束下不存在可达路径
     * </pre>
     *
     * <code>SCENE_PATH_NOT_FOUND = 6005;</code>
     */
    SCENE_PATH_NOT_FOUND(6005),
    /**
     * <pre>
     *寻路超过最大搜索节点数
     * </pre>
     *
     * <code>SCENE_PATH_LIMIT_EXCEEDED = 6006;</code>
     */
    SCENE_PATH_LIMIT_EXCEEDED(6006),
    /**
     * <pre>
     *目标点不在允许的战争迷雾范围内
     * </pre>
     *
     * <code>SCENE_FOG_BLOCKED = 6007;</code>
     */
    SCENE_FOG_BLOCKED(6007),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>Ok = 0;</code>
     */
    public static final int Ok_VALUE = 0;
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>FAILED = 1;</code>
     */
    public static final int FAILED_VALUE = 1;
    /**
     * <pre>
     *系统错误
     * </pre>
     *
     * <code>SYSTEM_ERROR = 2;</code>
     */
    public static final int SYSTEM_ERROR_VALUE = 2;
    /**
     * <pre>
     *参数错误
     * </pre>
     *
     * <code>PARAM_ERROR = 3;</code>
     */
    public static final int PARAM_ERROR_VALUE = 3;
    /**
     * <pre>
     *账号错误
     * </pre>
     *
     * <code>ACCOUNT_ERROR = 4;</code>
     */
    public static final int ACCOUNT_ERROR_VALUE = 4;
    /**
     * <pre>
     *密码错误
     * </pre>
     *
     * <code>PASSWORD_ERROR = 5;</code>
     */
    public static final int PASSWORD_ERROR_VALUE = 5;
    /**
     * <pre>
     *账号被禁用
     * </pre>
     *
     * <code>ACCOUNT_FORBIDDEN = 6;</code>
     */
    public static final int ACCOUNT_FORBIDDEN_VALUE = 6;
    /**
     * <pre>
     *账号已登录
     * </pre>
     *
     * <code>ACCOUNT_ONLINE = 7;</code>
     */
    public static final int ACCOUNT_ONLINE_VALUE = 7;
    /**
     * <pre>
     *账号未注册
     * </pre>
     *
     * <code>ACCOUNT_NOT_REGISTER = 8;</code>
     */
    public static final int ACCOUNT_NOT_REGISTER_VALUE = 8;
    /**
     * <pre>
     *玩家名已存在
     * </pre>
     *
     * <code>PLAYER_NAME_EXISTS = 9;</code>
     */
    public static final int PLAYER_NAME_EXISTS_VALUE = 9;
    /**
     * <pre>
     *token错误
     * </pre>
     *
     * <code>TOKEN_ERROR = 10;</code>
     */
    public static final int TOKEN_ERROR_VALUE = 10;
    /**
     * <pre>
     *玩家不存在
     * </pre>
     *
     * <code>PLAYER_NOT_EXIST = 11;</code>
     */
    public static final int PLAYER_NOT_EXIST_VALUE = 11;
    /**
     * <pre>
     * 英雄相关错误码 5000-5099
     * </pre>
     *
     * <code>HERO_NOT_FOUND = 5001;</code>
     */
    public static final int HERO_NOT_FOUND_VALUE = 5001;
    /**
     * <pre>
     *英雄不属于当前玩家
     * </pre>
     *
     * <code>HERO_NOT_BELONG = 5002;</code>
     */
    public static final int HERO_NOT_BELONG_VALUE = 5002;
    /**
     * <pre>
     *资源不足
     * </pre>
     *
     * <code>RESOURCE_NOT_ENOUGH = 5003;</code>
     */
    public static final int RESOURCE_NOT_ENOUGH_VALUE = 5003;
    /**
     * <pre>
     *等级已达上限
     * </pre>
     *
     * <code>LEVEL_MAX = 5004;</code>
     */
    public static final int LEVEL_MAX_VALUE = 5004;
    /**
     * <pre>
     *星级已达上限
     * </pre>
     *
     * <code>STAR_MAX = 5005;</code>
     */
    public static final int STAR_MAX_VALUE = 5005;
    /**
     * <pre>
     *觉醒已达上限
     * </pre>
     *
     * <code>AWAKEN_MAX = 5006;</code>
     */
    public static final int AWAKEN_MAX_VALUE = 5006;
    /**
     * <pre>
     *升星条件不满足
     * </pre>
     *
     * <code>STAR_CONDITION_NOT_MET = 5007;</code>
     */
    public static final int STAR_CONDITION_NOT_MET_VALUE = 5007;
    /**
     * <pre>
     *觉醒条件不满足
     * </pre>
     *
     * <code>AWAKEN_CONDITION_NOT_MET = 5008;</code>
     */
    public static final int AWAKEN_CONDITION_NOT_MET_VALUE = 5008;
    /**
     * <pre>
     *英雄槽位已满
     * </pre>
     *
     * <code>HERO_SLOT_FULL = 5009;</code>
     */
    public static final int HERO_SLOT_FULL_VALUE = 5009;
    /**
     * <pre>
     *英雄已存在
     * </pre>
     *
     * <code>HERO_ALREADY_EXISTS = 5010;</code>
     */
    public static final int HERO_ALREADY_EXISTS_VALUE = 5010;
    /**
     * <pre>
     * 场景相关错误码 6000-6099
     * </pre>
     *
     * <code>SCENE_NOT_FOUND = 6001;</code>
     */
    public static final int SCENE_NOT_FOUND_VALUE = 6001;
    /**
     * <pre>
     *场景坐标越界
     * </pre>
     *
     * <code>SCENE_OUT_OF_BOUNDS = 6002;</code>
     */
    public static final int SCENE_OUT_OF_BOUNDS_VALUE = 6002;
    /**
     * <pre>
     *场景尚未完成启动或恢复
     * </pre>
     *
     * <code>SCENE_NOT_READY = 6003;</code>
     */
    public static final int SCENE_NOT_READY_VALUE = 6003;
    /**
     * <pre>
     *当前阶段不支持该场景操作
     * </pre>
     *
     * <code>SCENE_UNSUPPORTED = 6004;</code>
     */
    public static final int SCENE_UNSUPPORTED_VALUE = 6004;
    /**
     * <pre>
     *地形阻挡或约束下不存在可达路径
     * </pre>
     *
     * <code>SCENE_PATH_NOT_FOUND = 6005;</code>
     */
    public static final int SCENE_PATH_NOT_FOUND_VALUE = 6005;
    /**
     * <pre>
     *寻路超过最大搜索节点数
     * </pre>
     *
     * <code>SCENE_PATH_LIMIT_EXCEEDED = 6006;</code>
     */
    public static final int SCENE_PATH_LIMIT_EXCEEDED_VALUE = 6006;
    /**
     * <pre>
     *目标点不在允许的战争迷雾范围内
     * </pre>
     *
     * <code>SCENE_FOG_BLOCKED = 6007;</code>
     */
    public static final int SCENE_FOG_BLOCKED_VALUE = 6007;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return Ok;
        case 1: return FAILED;
        case 2: return SYSTEM_ERROR;
        case 3: return PARAM_ERROR;
        case 4: return ACCOUNT_ERROR;
        case 5: return PASSWORD_ERROR;
        case 6: return ACCOUNT_FORBIDDEN;
        case 7: return ACCOUNT_ONLINE;
        case 8: return ACCOUNT_NOT_REGISTER;
        case 9: return PLAYER_NAME_EXISTS;
        case 10: return TOKEN_ERROR;
        case 11: return PLAYER_NOT_EXIST;
        case 5001: return HERO_NOT_FOUND;
        case 5002: return HERO_NOT_BELONG;
        case 5003: return RESOURCE_NOT_ENOUGH;
        case 5004: return LEVEL_MAX;
        case 5005: return STAR_MAX;
        case 5006: return AWAKEN_MAX;
        case 5007: return STAR_CONDITION_NOT_MET;
        case 5008: return AWAKEN_CONDITION_NOT_MET;
        case 5009: return HERO_SLOT_FULL;
        case 5010: return HERO_ALREADY_EXISTS;
        case 6001: return SCENE_NOT_FOUND;
        case 6002: return SCENE_OUT_OF_BOUNDS;
        case 6003: return SCENE_NOT_READY;
        case 6004: return SCENE_UNSUPPORTED;
        case 6005: return SCENE_PATH_NOT_FOUND;
        case 6006: return SCENE_PATH_LIMIT_EXCEEDED;
        case 6007: return SCENE_FOG_BLOCKED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ly.proto.ErrorMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ErrorCode)
  }

  public interface csErrorCodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:csErrorCode)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code csErrorCode}
   */
  public static final class csErrorCode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:csErrorCode)
      csErrorCodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use csErrorCode.newBuilder() to construct.
    private csErrorCode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private csErrorCode() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new csErrorCode();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ly.proto.ErrorMsg.internal_static_csErrorCode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ly.proto.ErrorMsg.internal_static_csErrorCode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ly.proto.ErrorMsg.csErrorCode.class, ly.proto.ErrorMsg.csErrorCode.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ly.proto.ErrorMsg.csErrorCode)) {
        return super.equals(obj);
      }
      ly.proto.ErrorMsg.csErrorCode other = (ly.proto.ErrorMsg.csErrorCode) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ly.proto.ErrorMsg.csErrorCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ly.proto.ErrorMsg.csErrorCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.ErrorMsg.csErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ly.proto.ErrorMsg.csErrorCode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code csErrorCode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:csErrorCode)
        ly.proto.ErrorMsg.csErrorCodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ly.proto.ErrorMsg.internal_static_csErrorCode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ly.proto.ErrorMsg.internal_static_csErrorCode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ly.proto.ErrorMsg.csErrorCode.class, ly.proto.ErrorMsg.csErrorCode.Builder.class);
      }

      // Construct using ly.proto.ErrorMsg.csErrorCode.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ly.proto.ErrorMsg.internal_static_csErrorCode_descriptor;
      }

      @java.lang.Override
      public ly.proto.ErrorMsg.csErrorCode getDefaultInstanceForType() {
        return ly.proto.ErrorMsg.csErrorCode.getDefaultInstance();
      }

      @java.lang.Override
      public ly.proto.ErrorMsg.csErrorCode build() {
        ly.proto.ErrorMsg.csErrorCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ly.proto.ErrorMsg.csErrorCode buildPartial() {
        ly.proto.ErrorMsg.csErrorCode result = new ly.proto.ErrorMsg.csErrorCode(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ly.proto.ErrorMsg.csErrorCode) {
          return mergeFrom((ly.proto.ErrorMsg.csErrorCode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ly.proto.ErrorMsg.csErrorCode other) {
        if (other == ly.proto.ErrorMsg.csErrorCode.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:csErrorCode)
    }

    // @@protoc_insertion_point(class_scope:csErrorCode)
    private static final ly.proto.ErrorMsg.csErrorCode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ly.proto.ErrorMsg.csErrorCode();
    }

    public static ly.proto.ErrorMsg.csErrorCode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<csErrorCode>
        PARSER = new com.google.protobuf.AbstractParser<csErrorCode>() {
      @java.lang.Override
      public csErrorCode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<csErrorCode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<csErrorCode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ly.proto.ErrorMsg.csErrorCode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface scErrorCodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:scErrorCode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *产生错误的消息号
     * </pre>
     *
     * <code>int32 msgId = 1;</code>
     * @return The msgId.
     */
    int getMsgId();

    /**
     * <pre>
     *错误码
     * </pre>
     *
     * <code>.ErrorCode errorCode = 2;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    int getErrorCodeValue();
    /**
     * <pre>
     *错误码
     * </pre>
     *
     * <code>.ErrorCode errorCode = 2;</code>
     * @return The errorCode.
     */
    ly.proto.ErrorMsg.ErrorCode getErrorCode();
  }
  /**
   * Protobuf type {@code scErrorCode}
   */
  public static final class scErrorCode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:scErrorCode)
      scErrorCodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use scErrorCode.newBuilder() to construct.
    private scErrorCode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private scErrorCode() {
      errorCode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new scErrorCode();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ly.proto.ErrorMsg.internal_static_scErrorCode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ly.proto.ErrorMsg.internal_static_scErrorCode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ly.proto.ErrorMsg.scErrorCode.class, ly.proto.ErrorMsg.scErrorCode.Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgId_ = 0;
    /**
     * <pre>
     *产生错误的消息号
     * </pre>
     *
     * <code>int32 msgId = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public int getMsgId() {
      return msgId_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_ = 0;
    /**
     * <pre>
     *错误码
     * </pre>
     *
     * <code>.ErrorCode errorCode = 2;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    @java.lang.Override public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <pre>
     *错误码
     * </pre>
     *
     * <code>.ErrorCode errorCode = 2;</code>
     * @return The errorCode.
     */
    @java.lang.Override public ly.proto.ErrorMsg.ErrorCode getErrorCode() {
      ly.proto.ErrorMsg.ErrorCode result = ly.proto.ErrorMsg.ErrorCode.forNumber(errorCode_);
      return result == null ? ly.proto.ErrorMsg.ErrorCode.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0) {
        output.writeInt32(1, msgId_);
      }
      if (errorCode_ != ly.proto.ErrorMsg.ErrorCode.Ok.getNumber()) {
        output.writeEnum(2, errorCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      if (errorCode_ != ly.proto.ErrorMsg.ErrorCode.Ok.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, errorCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ly.proto.ErrorMsg.scErrorCode)) {
        return super.equals(obj);
      }
      ly.proto.ErrorMsg.scErrorCode other = (ly.proto.ErrorMsg.scErrorCode) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (errorCode_ != other.errorCode_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + errorCode_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ly.proto.ErrorMsg.scErrorCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ly.proto.ErrorMsg.scErrorCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.ErrorMsg.scErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ly.proto.ErrorMsg.scErrorCode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scErrorCode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:scErrorCode)
        ly.proto.ErrorMsg.scErrorCodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ly.proto.ErrorMsg.internal_static_scErrorCode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ly.proto.ErrorMsg.internal_static_scErrorCode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ly.proto.ErrorMsg.scErrorCode.class, ly.proto.ErrorMsg.scErrorCode.Builder.class);
      }

      // Construct using ly.proto.ErrorMsg.scErrorCode.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgId_ = 0;
        errorCode_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ly.proto.ErrorMsg.internal_static_scErrorCode_descriptor;
      }

      @java.lang.Override
      public ly.proto.ErrorMsg.scErrorCode getDefaultInstanceForType() {
        return ly.proto.ErrorMsg.scErrorCode.getDefaultInstance();
      }

      @java.lang.Override
      public ly.proto.ErrorMsg.scErrorCode build() {
        ly.proto.ErrorMsg.scErrorCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ly.proto.ErrorMsg.scErrorCode buildPartial() {
        ly.proto.ErrorMsg.scErrorCode result = new ly.proto.ErrorMsg.scErrorCode(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ly.proto.ErrorMsg.scErrorCode result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgId_ = msgId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.errorCode_ = errorCode_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ly.proto.ErrorMsg.scErrorCode) {
          return mergeFrom((ly.proto.ErrorMsg.scErrorCode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ly.proto.ErrorMsg.scErrorCode other) {
        if (other == ly.proto.ErrorMsg.scErrorCode.getDefaultInstance()) return this;
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (other.errorCode_ != 0) {
          setErrorCodeValue(other.getErrorCodeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                errorCode_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int msgId_ ;
      /**
       * <pre>
       *产生错误的消息号
       * </pre>
       *
       * <code>int32 msgId = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *产生错误的消息号
       * </pre>
       *
       * <code>int32 msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(int value) {

        msgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *产生错误的消息号
       * </pre>
       *
       * <code>int32 msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ = 0;
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>.ErrorCode errorCode = 2;</code>
       * @return The enum numeric value on the wire for errorCode.
       */
      @java.lang.Override public int getErrorCodeValue() {
        return errorCode_;
      }
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>.ErrorCode errorCode = 2;</code>
       * @param value The enum numeric value on the wire for errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCodeValue(int value) {
        errorCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>.ErrorCode errorCode = 2;</code>
       * @return The errorCode.
       */
      @java.lang.Override
      public ly.proto.ErrorMsg.ErrorCode getErrorCode() {
        ly.proto.ErrorMsg.ErrorCode result = ly.proto.ErrorMsg.ErrorCode.forNumber(errorCode_);
        return result == null ? ly.proto.ErrorMsg.ErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>.ErrorCode errorCode = 2;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(ly.proto.ErrorMsg.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        errorCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>.ErrorCode errorCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:scErrorCode)
    }

    // @@protoc_insertion_point(class_scope:scErrorCode)
    private static final ly.proto.ErrorMsg.scErrorCode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ly.proto.ErrorMsg.scErrorCode();
    }

    public static ly.proto.ErrorMsg.scErrorCode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<scErrorCode>
        PARSER = new com.google.protobuf.AbstractParser<scErrorCode>() {
      @java.lang.Override
      public scErrorCode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<scErrorCode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<scErrorCode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ly.proto.ErrorMsg.scErrorCode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_csErrorCode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_csErrorCode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scErrorCode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scErrorCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ErrorMsg.proto\"\r\n\013csErrorCode\";\n\013scErr" +
      "orCode\022\r\n\005msgId\030\001 \001(\005\022\035\n\terrorCode\030\002 \001(\016" +
      "2\n.ErrorCode*\376\004\n\tErrorCode\022\006\n\002Ok\020\000\022\n\n\006FA" +
      "ILED\020\001\022\020\n\014SYSTEM_ERROR\020\002\022\017\n\013PARAM_ERROR\020" +
      "\003\022\021\n\rACCOUNT_ERROR\020\004\022\022\n\016PASSWORD_ERROR\020\005" +
      "\022\025\n\021ACCOUNT_FORBIDDEN\020\006\022\022\n\016ACCOUNT_ONLIN" +
      "E\020\007\022\030\n\024ACCOUNT_NOT_REGISTER\020\010\022\026\n\022PLAYER_" +
      "NAME_EXISTS\020\t\022\017\n\013TOKEN_ERROR\020\n\022\024\n\020PLAYER" +
      "_NOT_EXIST\020\013\022\023\n\016HERO_NOT_FOUND\020\211\'\022\024\n\017HER" +
      "O_NOT_BELONG\020\212\'\022\030\n\023RESOURCE_NOT_ENOUGH\020\213" +
      "\'\022\016\n\tLEVEL_MAX\020\214\'\022\r\n\010STAR_MAX\020\215\'\022\017\n\nAWAK" +
      "EN_MAX\020\216\'\022\033\n\026STAR_CONDITION_NOT_MET\020\217\'\022\035" +
      "\n\030AWAKEN_CONDITION_NOT_MET\020\220\'\022\023\n\016HERO_SL" +
      "OT_FULL\020\221\'\022\030\n\023HERO_ALREADY_EXISTS\020\222\'\022\024\n\017" +
      "SCENE_NOT_FOUND\020\361.\022\030\n\023SCENE_OUT_OF_BOUND" +
      "S\020\362.\022\024\n\017SCENE_NOT_READY\020\363.\022\026\n\021SCENE_UNSU" +
      "PPORTED\020\364.\022\031\n\024SCENE_PATH_NOT_FOUND\020\365.\022\036\n" +
      "\031SCENE_PATH_LIMIT_EXCEEDED\020\366.\022\026\n\021SCENE_F" +
      "OG_BLOCKED\020\367.B\n\n\010ly.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_csErrorCode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_csErrorCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_csErrorCode_descriptor,
        new java.lang.String[] { });
    internal_static_scErrorCode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scErrorCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scErrorCode_descriptor,
        new java.lang.String[] { "MsgId", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
