// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Move.proto

package ly.proto;

public final class Move {
  private Move() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CS_MoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CS_Move)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 目标X坐标
     * </pre>
     *
     * <code>int32 target_x = 1;</code>
     * @return The targetX.
     */
    int getTargetX();

    /**
     * <pre>
     * 目标Y坐标
     * </pre>
     *
     * <code>int32 target_y = 2;</code>
     * @return The targetY.
     */
    int getTargetY();
  }
  /**
   * <pre>
   * 移动请求
   * </pre>
   *
   * Protobuf type {@code CS_Move}
   */
  public static final class CS_Move extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CS_Move)
      CS_MoveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CS_Move.newBuilder() to construct.
    private CS_Move(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS_Move() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CS_Move();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CS_Move(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              targetX_ = input.readInt32();
              break;
            }
            case 16: {

              targetY_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ly.proto.Move.internal_static_CS_Move_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ly.proto.Move.internal_static_CS_Move_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ly.proto.Move.CS_Move.class, ly.proto.Move.CS_Move.Builder.class);
    }

    public static final int TARGET_X_FIELD_NUMBER = 1;
    private int targetX_;
    /**
     * <pre>
     * 目标X坐标
     * </pre>
     *
     * <code>int32 target_x = 1;</code>
     * @return The targetX.
     */
    @java.lang.Override
    public int getTargetX() {
      return targetX_;
    }

    public static final int TARGET_Y_FIELD_NUMBER = 2;
    private int targetY_;
    /**
     * <pre>
     * 目标Y坐标
     * </pre>
     *
     * <code>int32 target_y = 2;</code>
     * @return The targetY.
     */
    @java.lang.Override
    public int getTargetY() {
      return targetY_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (targetX_ != 0) {
        output.writeInt32(1, targetX_);
      }
      if (targetY_ != 0) {
        output.writeInt32(2, targetY_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (targetX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, targetX_);
      }
      if (targetY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, targetY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ly.proto.Move.CS_Move)) {
        return super.equals(obj);
      }
      ly.proto.Move.CS_Move other = (ly.proto.Move.CS_Move) obj;

      if (getTargetX()
          != other.getTargetX()) return false;
      if (getTargetY()
          != other.getTargetY()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGET_X_FIELD_NUMBER;
      hash = (53 * hash) + getTargetX();
      hash = (37 * hash) + TARGET_Y_FIELD_NUMBER;
      hash = (53 * hash) + getTargetY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ly.proto.Move.CS_Move parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.CS_Move parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.CS_Move parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.CS_Move parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.CS_Move parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.CS_Move parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.CS_Move parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.CS_Move parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.Move.CS_Move parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ly.proto.Move.CS_Move parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.Move.CS_Move parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.CS_Move parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ly.proto.Move.CS_Move prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 移动请求
     * </pre>
     *
     * Protobuf type {@code CS_Move}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CS_Move)
        ly.proto.Move.CS_MoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ly.proto.Move.internal_static_CS_Move_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ly.proto.Move.internal_static_CS_Move_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ly.proto.Move.CS_Move.class, ly.proto.Move.CS_Move.Builder.class);
      }

      // Construct using ly.proto.Move.CS_Move.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        targetX_ = 0;

        targetY_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ly.proto.Move.internal_static_CS_Move_descriptor;
      }

      @java.lang.Override
      public ly.proto.Move.CS_Move getDefaultInstanceForType() {
        return ly.proto.Move.CS_Move.getDefaultInstance();
      }

      @java.lang.Override
      public ly.proto.Move.CS_Move build() {
        ly.proto.Move.CS_Move result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ly.proto.Move.CS_Move buildPartial() {
        ly.proto.Move.CS_Move result = new ly.proto.Move.CS_Move(this);
        result.targetX_ = targetX_;
        result.targetY_ = targetY_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ly.proto.Move.CS_Move) {
          return mergeFrom((ly.proto.Move.CS_Move)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ly.proto.Move.CS_Move other) {
        if (other == ly.proto.Move.CS_Move.getDefaultInstance()) return this;
        if (other.getTargetX() != 0) {
          setTargetX(other.getTargetX());
        }
        if (other.getTargetY() != 0) {
          setTargetY(other.getTargetY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ly.proto.Move.CS_Move parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ly.proto.Move.CS_Move) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int targetX_ ;
      /**
       * <pre>
       * 目标X坐标
       * </pre>
       *
       * <code>int32 target_x = 1;</code>
       * @return The targetX.
       */
      @java.lang.Override
      public int getTargetX() {
        return targetX_;
      }
      /**
       * <pre>
       * 目标X坐标
       * </pre>
       *
       * <code>int32 target_x = 1;</code>
       * @param value The targetX to set.
       * @return This builder for chaining.
       */
      public Builder setTargetX(int value) {
        
        targetX_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标X坐标
       * </pre>
       *
       * <code>int32 target_x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetX() {
        
        targetX_ = 0;
        onChanged();
        return this;
      }

      private int targetY_ ;
      /**
       * <pre>
       * 目标Y坐标
       * </pre>
       *
       * <code>int32 target_y = 2;</code>
       * @return The targetY.
       */
      @java.lang.Override
      public int getTargetY() {
        return targetY_;
      }
      /**
       * <pre>
       * 目标Y坐标
       * </pre>
       *
       * <code>int32 target_y = 2;</code>
       * @param value The targetY to set.
       * @return This builder for chaining.
       */
      public Builder setTargetY(int value) {
        
        targetY_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标Y坐标
       * </pre>
       *
       * <code>int32 target_y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetY() {
        
        targetY_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CS_Move)
    }

    // @@protoc_insertion_point(class_scope:CS_Move)
    private static final ly.proto.Move.CS_Move DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ly.proto.Move.CS_Move();
    }

    public static ly.proto.Move.CS_Move getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CS_Move>
        PARSER = new com.google.protobuf.AbstractParser<CS_Move>() {
      @java.lang.Override
      public CS_Move parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS_Move(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS_Move> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS_Move> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ly.proto.Move.CS_Move getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC_MoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SC_Move)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The result.
     */
    ly.proto.ErrorMsg.ErrorCode getResult();

    /**
     * <pre>
     * 当前X坐标
     * </pre>
     *
     * <code>int32 current_x = 2;</code>
     * @return The currentX.
     */
    int getCurrentX();

    /**
     * <pre>
     * 当前Y坐标
     * </pre>
     *
     * <code>int32 current_y = 3;</code>
     * @return The currentY.
     */
    int getCurrentY();
  }
  /**
   * <pre>
   * 移动响应
   * </pre>
   *
   * Protobuf type {@code SC_Move}
   */
  public static final class SC_Move extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SC_Move)
      SC_MoveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC_Move.newBuilder() to construct.
    private SC_Move(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_Move() {
      result_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SC_Move();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC_Move(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 16: {

              currentX_ = input.readInt32();
              break;
            }
            case 24: {

              currentY_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ly.proto.Move.internal_static_SC_Move_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ly.proto.Move.internal_static_SC_Move_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ly.proto.Move.SC_Move.class, ly.proto.Move.SC_Move.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The result.
     */
    @java.lang.Override public ly.proto.ErrorMsg.ErrorCode getResult() {
      @SuppressWarnings("deprecation")
      ly.proto.ErrorMsg.ErrorCode result = ly.proto.ErrorMsg.ErrorCode.valueOf(result_);
      return result == null ? ly.proto.ErrorMsg.ErrorCode.UNRECOGNIZED : result;
    }

    public static final int CURRENT_X_FIELD_NUMBER = 2;
    private int currentX_;
    /**
     * <pre>
     * 当前X坐标
     * </pre>
     *
     * <code>int32 current_x = 2;</code>
     * @return The currentX.
     */
    @java.lang.Override
    public int getCurrentX() {
      return currentX_;
    }

    public static final int CURRENT_Y_FIELD_NUMBER = 3;
    private int currentY_;
    /**
     * <pre>
     * 当前Y坐标
     * </pre>
     *
     * <code>int32 current_y = 3;</code>
     * @return The currentY.
     */
    @java.lang.Override
    public int getCurrentY() {
      return currentY_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != ly.proto.ErrorMsg.ErrorCode.Ok.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (currentX_ != 0) {
        output.writeInt32(2, currentX_);
      }
      if (currentY_ != 0) {
        output.writeInt32(3, currentY_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != ly.proto.ErrorMsg.ErrorCode.Ok.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (currentX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentX_);
      }
      if (currentY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ly.proto.Move.SC_Move)) {
        return super.equals(obj);
      }
      ly.proto.Move.SC_Move other = (ly.proto.Move.SC_Move) obj;

      if (result_ != other.result_) return false;
      if (getCurrentX()
          != other.getCurrentX()) return false;
      if (getCurrentY()
          != other.getCurrentY()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + CURRENT_X_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentX();
      hash = (37 * hash) + CURRENT_Y_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ly.proto.Move.SC_Move parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.SC_Move parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.SC_Move parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.SC_Move parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.SC_Move parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.SC_Move parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.SC_Move parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.SC_Move parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.Move.SC_Move parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ly.proto.Move.SC_Move parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.Move.SC_Move parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.SC_Move parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ly.proto.Move.SC_Move prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 移动响应
     * </pre>
     *
     * Protobuf type {@code SC_Move}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SC_Move)
        ly.proto.Move.SC_MoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ly.proto.Move.internal_static_SC_Move_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ly.proto.Move.internal_static_SC_Move_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ly.proto.Move.SC_Move.class, ly.proto.Move.SC_Move.Builder.class);
      }

      // Construct using ly.proto.Move.SC_Move.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        currentX_ = 0;

        currentY_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ly.proto.Move.internal_static_SC_Move_descriptor;
      }

      @java.lang.Override
      public ly.proto.Move.SC_Move getDefaultInstanceForType() {
        return ly.proto.Move.SC_Move.getDefaultInstance();
      }

      @java.lang.Override
      public ly.proto.Move.SC_Move build() {
        ly.proto.Move.SC_Move result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ly.proto.Move.SC_Move buildPartial() {
        ly.proto.Move.SC_Move result = new ly.proto.Move.SC_Move(this);
        result.result_ = result_;
        result.currentX_ = currentX_;
        result.currentY_ = currentY_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ly.proto.Move.SC_Move) {
          return mergeFrom((ly.proto.Move.SC_Move)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ly.proto.Move.SC_Move other) {
        if (other == ly.proto.Move.SC_Move.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (other.getCurrentX() != 0) {
          setCurrentX(other.getCurrentX());
        }
        if (other.getCurrentY() != 0) {
          setCurrentY(other.getCurrentY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ly.proto.Move.SC_Move parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ly.proto.Move.SC_Move) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.ErrorCode result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @java.lang.Override public int getResultValue() {
        return result_;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public ly.proto.ErrorMsg.ErrorCode getResult() {
        @SuppressWarnings("deprecation")
        ly.proto.ErrorMsg.ErrorCode result = ly.proto.ErrorMsg.ErrorCode.valueOf(result_);
        return result == null ? ly.proto.ErrorMsg.ErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(ly.proto.ErrorMsg.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int currentX_ ;
      /**
       * <pre>
       * 当前X坐标
       * </pre>
       *
       * <code>int32 current_x = 2;</code>
       * @return The currentX.
       */
      @java.lang.Override
      public int getCurrentX() {
        return currentX_;
      }
      /**
       * <pre>
       * 当前X坐标
       * </pre>
       *
       * <code>int32 current_x = 2;</code>
       * @param value The currentX to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentX(int value) {
        
        currentX_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前X坐标
       * </pre>
       *
       * <code>int32 current_x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentX() {
        
        currentX_ = 0;
        onChanged();
        return this;
      }

      private int currentY_ ;
      /**
       * <pre>
       * 当前Y坐标
       * </pre>
       *
       * <code>int32 current_y = 3;</code>
       * @return The currentY.
       */
      @java.lang.Override
      public int getCurrentY() {
        return currentY_;
      }
      /**
       * <pre>
       * 当前Y坐标
       * </pre>
       *
       * <code>int32 current_y = 3;</code>
       * @param value The currentY to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentY(int value) {
        
        currentY_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前Y坐标
       * </pre>
       *
       * <code>int32 current_y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentY() {
        
        currentY_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SC_Move)
    }

    // @@protoc_insertion_point(class_scope:SC_Move)
    private static final ly.proto.Move.SC_Move DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ly.proto.Move.SC_Move();
    }

    public static ly.proto.Move.SC_Move getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_Move>
        PARSER = new com.google.protobuf.AbstractParser<SC_Move>() {
      @java.lang.Override
      public SC_Move parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC_Move(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_Move> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_Move> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ly.proto.Move.SC_Move getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CS_Move_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CS_Move_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SC_Move_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SC_Move_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nMove.proto\032\016ErrorMsg.proto\"-\n\007CS_Move\022" +
      "\020\n\010target_x\030\001 \001(\005\022\020\n\010target_y\030\002 \001(\005\"K\n\007S" +
      "C_Move\022\032\n\006result\030\001 \001(\0162\n.ErrorCode\022\021\n\tcu" +
      "rrent_x\030\002 \001(\005\022\021\n\tcurrent_y\030\003 \001(\005B\n\n\010ly.p" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ly.proto.ErrorMsg.getDescriptor(),
        });
    internal_static_CS_Move_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CS_Move_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CS_Move_descriptor,
        new java.lang.String[] { "TargetX", "TargetY", });
    internal_static_SC_Move_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SC_Move_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SC_Move_descriptor,
        new java.lang.String[] { "Result", "CurrentX", "CurrentY", });
    ly.proto.ErrorMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
