// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Move.proto

// Protobuf Java Version: 3.25.6
package ly.proto;

public final class Move {
  private Move() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface csMoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:csMove)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 目标X坐标
     * </pre>
     *
     * <code>int32 target_x = 1;</code>
     * @return The targetX.
     */
    int getTargetX();

    /**
     * <pre>
     * 目标Y坐标
     * </pre>
     *
     * <code>int32 target_y = 2;</code>
     * @return The targetY.
     */
    int getTargetY();

    /**
     * <pre>
     * 协程测试用：需要在本次移动处理中读取的目标玩家
     * </pre>
     *
     * <code>int64 observe_player_id = 3;</code>
     * @return The observePlayerId.
     */
    long getObservePlayerId();
  }
  /**
   * <pre>
   * 移动请求
   * </pre>
   *
   * Protobuf type {@code csMove}
   */
  public static final class csMove extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:csMove)
      csMoveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use csMove.newBuilder() to construct.
    private csMove(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private csMove() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new csMove();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ly.proto.Move.internal_static_csMove_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ly.proto.Move.internal_static_csMove_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ly.proto.Move.csMove.class, ly.proto.Move.csMove.Builder.class);
    }

    public static final int TARGET_X_FIELD_NUMBER = 1;
    private int targetX_ = 0;
    /**
     * <pre>
     * 目标X坐标
     * </pre>
     *
     * <code>int32 target_x = 1;</code>
     * @return The targetX.
     */
    @java.lang.Override
    public int getTargetX() {
      return targetX_;
    }

    public static final int TARGET_Y_FIELD_NUMBER = 2;
    private int targetY_ = 0;
    /**
     * <pre>
     * 目标Y坐标
     * </pre>
     *
     * <code>int32 target_y = 2;</code>
     * @return The targetY.
     */
    @java.lang.Override
    public int getTargetY() {
      return targetY_;
    }

    public static final int OBSERVE_PLAYER_ID_FIELD_NUMBER = 3;
    private long observePlayerId_ = 0L;
    /**
     * <pre>
     * 协程测试用：需要在本次移动处理中读取的目标玩家
     * </pre>
     *
     * <code>int64 observe_player_id = 3;</code>
     * @return The observePlayerId.
     */
    @java.lang.Override
    public long getObservePlayerId() {
      return observePlayerId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (targetX_ != 0) {
        output.writeInt32(1, targetX_);
      }
      if (targetY_ != 0) {
        output.writeInt32(2, targetY_);
      }
      if (observePlayerId_ != 0L) {
        output.writeInt64(3, observePlayerId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (targetX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, targetX_);
      }
      if (targetY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, targetY_);
      }
      if (observePlayerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, observePlayerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ly.proto.Move.csMove)) {
        return super.equals(obj);
      }
      ly.proto.Move.csMove other = (ly.proto.Move.csMove) obj;

      if (getTargetX()
          != other.getTargetX()) return false;
      if (getTargetY()
          != other.getTargetY()) return false;
      if (getObservePlayerId()
          != other.getObservePlayerId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGET_X_FIELD_NUMBER;
      hash = (53 * hash) + getTargetX();
      hash = (37 * hash) + TARGET_Y_FIELD_NUMBER;
      hash = (53 * hash) + getTargetY();
      hash = (37 * hash) + OBSERVE_PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getObservePlayerId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ly.proto.Move.csMove parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.csMove parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.csMove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.csMove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.csMove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.csMove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.csMove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.csMove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ly.proto.Move.csMove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ly.proto.Move.csMove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.Move.csMove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.csMove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ly.proto.Move.csMove prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 移动请求
     * </pre>
     *
     * Protobuf type {@code csMove}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:csMove)
        ly.proto.Move.csMoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ly.proto.Move.internal_static_csMove_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ly.proto.Move.internal_static_csMove_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ly.proto.Move.csMove.class, ly.proto.Move.csMove.Builder.class);
      }

      // Construct using ly.proto.Move.csMove.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        targetX_ = 0;
        targetY_ = 0;
        observePlayerId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ly.proto.Move.internal_static_csMove_descriptor;
      }

      @java.lang.Override
      public ly.proto.Move.csMove getDefaultInstanceForType() {
        return ly.proto.Move.csMove.getDefaultInstance();
      }

      @java.lang.Override
      public ly.proto.Move.csMove build() {
        ly.proto.Move.csMove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ly.proto.Move.csMove buildPartial() {
        ly.proto.Move.csMove result = new ly.proto.Move.csMove(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ly.proto.Move.csMove result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.targetX_ = targetX_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.targetY_ = targetY_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.observePlayerId_ = observePlayerId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ly.proto.Move.csMove) {
          return mergeFrom((ly.proto.Move.csMove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ly.proto.Move.csMove other) {
        if (other == ly.proto.Move.csMove.getDefaultInstance()) return this;
        if (other.getTargetX() != 0) {
          setTargetX(other.getTargetX());
        }
        if (other.getTargetY() != 0) {
          setTargetY(other.getTargetY());
        }
        if (other.getObservePlayerId() != 0L) {
          setObservePlayerId(other.getObservePlayerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                targetX_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                targetY_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                observePlayerId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int targetX_ ;
      /**
       * <pre>
       * 目标X坐标
       * </pre>
       *
       * <code>int32 target_x = 1;</code>
       * @return The targetX.
       */
      @java.lang.Override
      public int getTargetX() {
        return targetX_;
      }
      /**
       * <pre>
       * 目标X坐标
       * </pre>
       *
       * <code>int32 target_x = 1;</code>
       * @param value The targetX to set.
       * @return This builder for chaining.
       */
      public Builder setTargetX(int value) {

        targetX_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标X坐标
       * </pre>
       *
       * <code>int32 target_x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetX_ = 0;
        onChanged();
        return this;
      }

      private int targetY_ ;
      /**
       * <pre>
       * 目标Y坐标
       * </pre>
       *
       * <code>int32 target_y = 2;</code>
       * @return The targetY.
       */
      @java.lang.Override
      public int getTargetY() {
        return targetY_;
      }
      /**
       * <pre>
       * 目标Y坐标
       * </pre>
       *
       * <code>int32 target_y = 2;</code>
       * @param value The targetY to set.
       * @return This builder for chaining.
       */
      public Builder setTargetY(int value) {

        targetY_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标Y坐标
       * </pre>
       *
       * <code>int32 target_y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        targetY_ = 0;
        onChanged();
        return this;
      }

      private long observePlayerId_ ;
      /**
       * <pre>
       * 协程测试用：需要在本次移动处理中读取的目标玩家
       * </pre>
       *
       * <code>int64 observe_player_id = 3;</code>
       * @return The observePlayerId.
       */
      @java.lang.Override
      public long getObservePlayerId() {
        return observePlayerId_;
      }
      /**
       * <pre>
       * 协程测试用：需要在本次移动处理中读取的目标玩家
       * </pre>
       *
       * <code>int64 observe_player_id = 3;</code>
       * @param value The observePlayerId to set.
       * @return This builder for chaining.
       */
      public Builder setObservePlayerId(long value) {

        observePlayerId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协程测试用：需要在本次移动处理中读取的目标玩家
       * </pre>
       *
       * <code>int64 observe_player_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearObservePlayerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        observePlayerId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:csMove)
    }

    // @@protoc_insertion_point(class_scope:csMove)
    private static final ly.proto.Move.csMove DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ly.proto.Move.csMove();
    }

    public static ly.proto.Move.csMove getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<csMove>
        PARSER = new com.google.protobuf.AbstractParser<csMove>() {
      @java.lang.Override
      public csMove parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<csMove> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<csMove> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ly.proto.Move.csMove getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface scMoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:scMove)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The result.
     */
    ly.proto.ErrorMsg.ErrorCode getResult();

    /**
     * <pre>
     * 当前X坐标
     * </pre>
     *
     * <code>int32 current_x = 2;</code>
     * @return The currentX.
     */
    int getCurrentX();

    /**
     * <pre>
     * 当前Y坐标
     * </pre>
     *
     * <code>int32 current_y = 3;</code>
     * @return The currentY.
     */
    int getCurrentY();

    /**
     * <pre>
     * 协程测试返回：被读取的目标玩家
     * </pre>
     *
     * <code>int64 observed_player_id = 4;</code>
     * @return The observedPlayerId.
     */
    long getObservedPlayerId();

    /**
     * <pre>
     * 协程测试返回：通过目标玩家队列读取到的等级
     * </pre>
     *
     * <code>int32 observed_level = 5;</code>
     * @return The observedLevel.
     */
    int getObservedLevel();
  }
  /**
   * <pre>
   * 移动响应
   * </pre>
   *
   * Protobuf type {@code scMove}
   */
  public static final class scMove extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:scMove)
      scMoveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use scMove.newBuilder() to construct.
    private scMove(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private scMove() {
      result_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new scMove();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ly.proto.Move.internal_static_scMove_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ly.proto.Move.internal_static_scMove_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ly.proto.Move.scMove.class, ly.proto.Move.scMove.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_ = 0;
    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.ErrorCode result = 1;</code>
     * @return The result.
     */
    @java.lang.Override public ly.proto.ErrorMsg.ErrorCode getResult() {
      ly.proto.ErrorMsg.ErrorCode result = ly.proto.ErrorMsg.ErrorCode.forNumber(result_);
      return result == null ? ly.proto.ErrorMsg.ErrorCode.UNRECOGNIZED : result;
    }

    public static final int CURRENT_X_FIELD_NUMBER = 2;
    private int currentX_ = 0;
    /**
     * <pre>
     * 当前X坐标
     * </pre>
     *
     * <code>int32 current_x = 2;</code>
     * @return The currentX.
     */
    @java.lang.Override
    public int getCurrentX() {
      return currentX_;
    }

    public static final int CURRENT_Y_FIELD_NUMBER = 3;
    private int currentY_ = 0;
    /**
     * <pre>
     * 当前Y坐标
     * </pre>
     *
     * <code>int32 current_y = 3;</code>
     * @return The currentY.
     */
    @java.lang.Override
    public int getCurrentY() {
      return currentY_;
    }

    public static final int OBSERVED_PLAYER_ID_FIELD_NUMBER = 4;
    private long observedPlayerId_ = 0L;
    /**
     * <pre>
     * 协程测试返回：被读取的目标玩家
     * </pre>
     *
     * <code>int64 observed_player_id = 4;</code>
     * @return The observedPlayerId.
     */
    @java.lang.Override
    public long getObservedPlayerId() {
      return observedPlayerId_;
    }

    public static final int OBSERVED_LEVEL_FIELD_NUMBER = 5;
    private int observedLevel_ = 0;
    /**
     * <pre>
     * 协程测试返回：通过目标玩家队列读取到的等级
     * </pre>
     *
     * <code>int32 observed_level = 5;</code>
     * @return The observedLevel.
     */
    @java.lang.Override
    public int getObservedLevel() {
      return observedLevel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != ly.proto.ErrorMsg.ErrorCode.Ok.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (currentX_ != 0) {
        output.writeInt32(2, currentX_);
      }
      if (currentY_ != 0) {
        output.writeInt32(3, currentY_);
      }
      if (observedPlayerId_ != 0L) {
        output.writeInt64(4, observedPlayerId_);
      }
      if (observedLevel_ != 0) {
        output.writeInt32(5, observedLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != ly.proto.ErrorMsg.ErrorCode.Ok.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (currentX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentX_);
      }
      if (currentY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentY_);
      }
      if (observedPlayerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, observedPlayerId_);
      }
      if (observedLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, observedLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ly.proto.Move.scMove)) {
        return super.equals(obj);
      }
      ly.proto.Move.scMove other = (ly.proto.Move.scMove) obj;

      if (result_ != other.result_) return false;
      if (getCurrentX()
          != other.getCurrentX()) return false;
      if (getCurrentY()
          != other.getCurrentY()) return false;
      if (getObservedPlayerId()
          != other.getObservedPlayerId()) return false;
      if (getObservedLevel()
          != other.getObservedLevel()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + CURRENT_X_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentX();
      hash = (37 * hash) + CURRENT_Y_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentY();
      hash = (37 * hash) + OBSERVED_PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getObservedPlayerId());
      hash = (37 * hash) + OBSERVED_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getObservedLevel();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ly.proto.Move.scMove parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.scMove parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.scMove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.scMove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.scMove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ly.proto.Move.scMove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ly.proto.Move.scMove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.scMove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ly.proto.Move.scMove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ly.proto.Move.scMove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ly.proto.Move.scMove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ly.proto.Move.scMove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ly.proto.Move.scMove prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 移动响应
     * </pre>
     *
     * Protobuf type {@code scMove}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:scMove)
        ly.proto.Move.scMoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ly.proto.Move.internal_static_scMove_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ly.proto.Move.internal_static_scMove_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ly.proto.Move.scMove.class, ly.proto.Move.scMove.Builder.class);
      }

      // Construct using ly.proto.Move.scMove.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = 0;
        currentX_ = 0;
        currentY_ = 0;
        observedPlayerId_ = 0L;
        observedLevel_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ly.proto.Move.internal_static_scMove_descriptor;
      }

      @java.lang.Override
      public ly.proto.Move.scMove getDefaultInstanceForType() {
        return ly.proto.Move.scMove.getDefaultInstance();
      }

      @java.lang.Override
      public ly.proto.Move.scMove build() {
        ly.proto.Move.scMove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ly.proto.Move.scMove buildPartial() {
        ly.proto.Move.scMove result = new ly.proto.Move.scMove(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ly.proto.Move.scMove result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.currentX_ = currentX_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.currentY_ = currentY_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.observedPlayerId_ = observedPlayerId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.observedLevel_ = observedLevel_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ly.proto.Move.scMove) {
          return mergeFrom((ly.proto.Move.scMove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ly.proto.Move.scMove other) {
        if (other == ly.proto.Move.scMove.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (other.getCurrentX() != 0) {
          setCurrentX(other.getCurrentX());
        }
        if (other.getCurrentY() != 0) {
          setCurrentY(other.getCurrentY());
        }
        if (other.getObservedPlayerId() != 0L) {
          setObservedPlayerId(other.getObservedPlayerId());
        }
        if (other.getObservedLevel() != 0) {
          setObservedLevel(other.getObservedLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                result_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                currentX_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                currentY_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                observedPlayerId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                observedLevel_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int result_ = 0;
      /**
       * <code>.ErrorCode result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @java.lang.Override public int getResultValue() {
        return result_;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public ly.proto.ErrorMsg.ErrorCode getResult() {
        ly.proto.ErrorMsg.ErrorCode result = ly.proto.ErrorMsg.ErrorCode.forNumber(result_);
        return result == null ? ly.proto.ErrorMsg.ErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(ly.proto.ErrorMsg.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ErrorCode result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      private int currentX_ ;
      /**
       * <pre>
       * 当前X坐标
       * </pre>
       *
       * <code>int32 current_x = 2;</code>
       * @return The currentX.
       */
      @java.lang.Override
      public int getCurrentX() {
        return currentX_;
      }
      /**
       * <pre>
       * 当前X坐标
       * </pre>
       *
       * <code>int32 current_x = 2;</code>
       * @param value The currentX to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentX(int value) {

        currentX_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前X坐标
       * </pre>
       *
       * <code>int32 current_x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentX_ = 0;
        onChanged();
        return this;
      }

      private int currentY_ ;
      /**
       * <pre>
       * 当前Y坐标
       * </pre>
       *
       * <code>int32 current_y = 3;</code>
       * @return The currentY.
       */
      @java.lang.Override
      public int getCurrentY() {
        return currentY_;
      }
      /**
       * <pre>
       * 当前Y坐标
       * </pre>
       *
       * <code>int32 current_y = 3;</code>
       * @param value The currentY to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentY(int value) {

        currentY_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前Y坐标
       * </pre>
       *
       * <code>int32 current_y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentY_ = 0;
        onChanged();
        return this;
      }

      private long observedPlayerId_ ;
      /**
       * <pre>
       * 协程测试返回：被读取的目标玩家
       * </pre>
       *
       * <code>int64 observed_player_id = 4;</code>
       * @return The observedPlayerId.
       */
      @java.lang.Override
      public long getObservedPlayerId() {
        return observedPlayerId_;
      }
      /**
       * <pre>
       * 协程测试返回：被读取的目标玩家
       * </pre>
       *
       * <code>int64 observed_player_id = 4;</code>
       * @param value The observedPlayerId to set.
       * @return This builder for chaining.
       */
      public Builder setObservedPlayerId(long value) {

        observedPlayerId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协程测试返回：被读取的目标玩家
       * </pre>
       *
       * <code>int64 observed_player_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearObservedPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        observedPlayerId_ = 0L;
        onChanged();
        return this;
      }

      private int observedLevel_ ;
      /**
       * <pre>
       * 协程测试返回：通过目标玩家队列读取到的等级
       * </pre>
       *
       * <code>int32 observed_level = 5;</code>
       * @return The observedLevel.
       */
      @java.lang.Override
      public int getObservedLevel() {
        return observedLevel_;
      }
      /**
       * <pre>
       * 协程测试返回：通过目标玩家队列读取到的等级
       * </pre>
       *
       * <code>int32 observed_level = 5;</code>
       * @param value The observedLevel to set.
       * @return This builder for chaining.
       */
      public Builder setObservedLevel(int value) {

        observedLevel_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协程测试返回：通过目标玩家队列读取到的等级
       * </pre>
       *
       * <code>int32 observed_level = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearObservedLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        observedLevel_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:scMove)
    }

    // @@protoc_insertion_point(class_scope:scMove)
    private static final ly.proto.Move.scMove DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ly.proto.Move.scMove();
    }

    public static ly.proto.Move.scMove getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<scMove>
        PARSER = new com.google.protobuf.AbstractParser<scMove>() {
      @java.lang.Override
      public scMove parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<scMove> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<scMove> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ly.proto.Move.scMove getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_csMove_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_csMove_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scMove_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scMove_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nMove.proto\032\016ErrorMsg.proto\"G\n\006csMove\022\020" +
      "\n\010target_x\030\001 \001(\005\022\020\n\010target_y\030\002 \001(\005\022\031\n\021ob" +
      "serve_player_id\030\003 \001(\003\"~\n\006scMove\022\032\n\006resul" +
      "t\030\001 \001(\0162\n.ErrorCode\022\021\n\tcurrent_x\030\002 \001(\005\022\021" +
      "\n\tcurrent_y\030\003 \001(\005\022\032\n\022observed_player_id\030" +
      "\004 \001(\003\022\026\n\016observed_level\030\005 \001(\005B\n\n\010ly.prot" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ly.proto.ErrorMsg.getDescriptor(),
        });
    internal_static_csMove_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_csMove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_csMove_descriptor,
        new java.lang.String[] { "TargetX", "TargetY", "ObservePlayerId", });
    internal_static_scMove_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scMove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scMove_descriptor,
        new java.lang.String[] { "Result", "CurrentX", "CurrentY", "ObservedPlayerId", "ObservedLevel", });
    ly.proto.ErrorMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
