server:
  port: 9090

spring:
  application:
    name: GMServer
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    ly: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
