CREATE TABLE IF NOT EXISTS `security_ban` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `ban_type` INT DEFAULT NULL,
  `target` VARCHAR(255) DEFAULT NULL,
  `reason` VARCHAR(255) DEFAULT NULL,
  `source` INT DEFAULT NULL,
  `status` INT DEFAULT NULL,
  `start_time` DATETIME DEFAULT NULL,
  `end_time` DATETIME DEFAULT NULL,
  `operator` VARCHAR(255) DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_config_version` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `version` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `switch_at_millis` BIGINT DEFAULT NULL,
  `operator` VARCHAR(255) DEFAULT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `game_item` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `item_type` INT DEFAULT NULL,
  `item_name` VARCHAR(255) DEFAULT NULL,
  `item_desc` VARCHAR(255) DEFAULT NULL,
  `quantity` INT DEFAULT NULL,
  `owner_id` BIGINT DEFAULT NULL,
  `acquire_time` DATETIME DEFAULT NULL,
  `expire_time` DATETIME DEFAULT NULL,
  `item_level` INT DEFAULT NULL,
  `enhance_count` INT DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_config_server_status` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `publish_id` VARCHAR(255) DEFAULT NULL,
  `version` VARCHAR(255) DEFAULT NULL,
  `server_id` VARCHAR(255) DEFAULT NULL,
  `server_type` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `error_msg` TEXT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `login` (
  `id` INT NOT NULL,
  `account` VARCHAR(255) DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `last_login_time` DATETIME DEFAULT NULL,
  `last_logout_time` DATETIME DEFAULT NULL,
  `token` VARCHAR(255) DEFAULT NULL,
  `channel` VARCHAR(255) DEFAULT NULL,
  `players` VARCHAR(255) DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `share_month` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `code` VARCHAR(255) DEFAULT NULL,
  `daily_time` DATE DEFAULT NULL,
  `open` VARCHAR(255) DEFAULT NULL,
  `high` VARCHAR(255) DEFAULT NULL,
  `low` VARCHAR(255) DEFAULT NULL,
  `close` VARCHAR(255) DEFAULT NULL,
  `preclose` VARCHAR(255) DEFAULT NULL,
  `volume` BIGINT DEFAULT NULL,
  `amount` BIGINT DEFAULT NULL,
  `adjustflag` INT DEFAULT NULL,
  `turn` VARCHAR(255) DEFAULT NULL,
  `pctChg` VARCHAR(255) DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_role_menu` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `role_id` INT DEFAULT NULL,
  `menu_id` INT DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_admin` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `username` VARCHAR(255) DEFAULT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `role_id` INT DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `share_enum_config` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `code` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `config_desc` VARCHAR(255) DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_info` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `username` VARCHAR(255) DEFAULT NULL,
  `nickname` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `phone` VARCHAR(255) DEFAULT NULL,
  `register_time` DATETIME DEFAULT NULL,
  `last_login_time` DATETIME DEFAULT NULL,
  `level` INT DEFAULT NULL,
  `exp` INT DEFAULT NULL,
  `status` INT DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_config_file` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `version` VARCHAR(255) DEFAULT NULL,
  `file_name` VARCHAR(255) DEFAULT NULL,
  `content` LONGTEXT DEFAULT NULL,
  `content_md5` VARCHAR(255) DEFAULT NULL,
  `file_size` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_menu` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `permission` VARCHAR(255) DEFAULT NULL,
  `parent_id` INT DEFAULT NULL,
  `path` VARCHAR(255) DEFAULT NULL,
  `icon` VARCHAR(255) DEFAULT NULL,
  `sort_order` INT DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_role_permission` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `role_id` INT DEFAULT NULL,
  `permission` VARCHAR(255) DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_operation_log` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `admin_id` BIGINT DEFAULT NULL,
  `username` VARCHAR(255) DEFAULT NULL,
  `action` VARCHAR(255) DEFAULT NULL,
  `target_type` VARCHAR(255) DEFAULT NULL,
  `target_id` VARCHAR(255) DEFAULT NULL,
  `detail` VARCHAR(255) DEFAULT NULL,
  `ip` VARCHAR(255) DEFAULT NULL,
  `result` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `share_week` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `code` VARCHAR(255) DEFAULT NULL,
  `daily_time` DATE DEFAULT NULL,
  `open` VARCHAR(255) DEFAULT NULL,
  `high` VARCHAR(255) DEFAULT NULL,
  `low` VARCHAR(255) DEFAULT NULL,
  `close` VARCHAR(255) DEFAULT NULL,
  `preclose` VARCHAR(255) DEFAULT NULL,
  `volume` BIGINT DEFAULT NULL,
  `amount` BIGINT DEFAULT NULL,
  `adjustflag` INT DEFAULT NULL,
  `turn` VARCHAR(255) DEFAULT NULL,
  `pctChg` VARCHAR(255) DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `security_event_log` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `event_type` INT DEFAULT NULL,
  `server_id` VARCHAR(255) DEFAULT NULL,
  `ip` VARCHAR(255) DEFAULT NULL,
  `account` VARCHAR(255) DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `player_id` BIGINT DEFAULT NULL,
  `cmd` INT DEFAULT NULL,
  `sid` INT DEFAULT NULL,
  `seq` INT DEFAULT NULL,
  `reason` VARCHAR(255) DEFAULT NULL,
  `extra` VARCHAR(255) DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gm_role` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `player` (
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `createTime` DATETIME DEFAULT NULL,
  `loginTime` DATETIME DEFAULT NULL,
  `logoutTime` DATETIME DEFAULT NULL,
  `level` INT DEFAULT NULL,
  `vipLevel` INT DEFAULT NULL,
  `modules` BLOB DEFAULT NULL,
  `guidId` BIGINT DEFAULT NULL,
  `account` VARCHAR(255) DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `share_daily` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `code` VARCHAR(255) DEFAULT NULL,
  `daily_time` DATE DEFAULT NULL,
  `open` VARCHAR(255) DEFAULT NULL,
  `high` VARCHAR(255) DEFAULT NULL,
  `low` VARCHAR(255) DEFAULT NULL,
  `close` VARCHAR(255) DEFAULT NULL,
  `preclose` VARCHAR(255) DEFAULT NULL,
  `volume` BIGINT DEFAULT NULL,
  `amount` BIGINT DEFAULT NULL,
  `adjustflag` INT DEFAULT NULL,
  `turn` VARCHAR(255) DEFAULT NULL,
  `tradestatus` INT DEFAULT NULL,
  `pctChg` VARCHAR(255) DEFAULT NULL,
  `peTTM` VARCHAR(255) DEFAULT NULL,
  `pbMRQ` VARCHAR(255) DEFAULT NULL,
  `psTTM` VARCHAR(255) DEFAULT NULL,
  `pcfNcfTTM` VARCHAR(255) DEFAULT NULL,
  `isST` INT DEFAULT NULL
,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

