package ly.config;

import java.util.List;
import ly.AbstractConfigChecker;
import ly.ConfigColumnMeta;

/** 自动生成的配置表检测基类，请不要手动修改。 */
public abstract class HeroAttrConfigCheckerBase extends AbstractConfigChecker<HeroAttrConfig> {
  @Override
  public String getConfigFileName() {
    return "heroAttr.txt";
  }

  @Override
  public List<ConfigColumnMeta> getExpectedColumns() {
    return List.of(
        new ConfigColumnMeta(0, "modelName", "INT"),
        new ConfigColumnMeta(1, "level", "INT"),
        new ConfigColumnMeta(2, "maxHP", "LIST<INT>"),
        new ConfigColumnMeta(3, "attack", "LIST<INT>"),
        new ConfigColumnMeta(4, "defence", "LIST<INT>"),
        new ConfigColumnMeta(5, "speed", "LIST<INT>"),
        new ConfigColumnMeta(6, "crit", "LIST<INT>"),
        new ConfigColumnMeta(7, "critRatio", "LIST<INT>"),
        new ConfigColumnMeta(8, "effectHit", "LIST<INT>"),
        new ConfigColumnMeta(9, "effectDodge", "LIST<INT>"),
        new ConfigColumnMeta(10, "maxHP2", "INT"),
        new ConfigColumnMeta(11, "attack2", "INT"),
        new ConfigColumnMeta(12, "defence2", "INT"),
        new ConfigColumnMeta(13, "speed2", "INT"),
        new ConfigColumnMeta(14, "crit2", "INT"),
        new ConfigColumnMeta(15, "critRatio2", "INT"),
        new ConfigColumnMeta(16, "effectHit2", "INT"),
        new ConfigColumnMeta(17, "effectDodge2", "INT"),
        new ConfigColumnMeta(18, "maxHP3", "INT"),
        new ConfigColumnMeta(19, "attack3", "INT"),
        new ConfigColumnMeta(20, "defence3", "INT"),
        new ConfigColumnMeta(21, "speed3", "INT"),
        new ConfigColumnMeta(22, "crit3", "INT"),
        new ConfigColumnMeta(23, "critRatio3", "INT"),
        new ConfigColumnMeta(24, "effectHit3", "INT"),
        new ConfigColumnMeta(25, "effectDodge3", "INT"),
        new ConfigColumnMeta(26, "maxHP4", "INT"),
        new ConfigColumnMeta(27, "attack4", "INT"),
        new ConfigColumnMeta(28, "defence4", "INT"),
        new ConfigColumnMeta(29, "speed4", "INT"),
        new ConfigColumnMeta(30, "crit4", "INT"),
        new ConfigColumnMeta(31, "critRatio4", "INT"),
        new ConfigColumnMeta(32, "effectHit4", "INT"),
        new ConfigColumnMeta(33, "effectDodge4", "INT"),
        new ConfigColumnMeta(34, "maxHP5", "INT"),
        new ConfigColumnMeta(35, "attack5", "INT"),
        new ConfigColumnMeta(36, "defence5", "INT"),
        new ConfigColumnMeta(37, "speed5", "INT"),
        new ConfigColumnMeta(38, "crit5", "INT"),
        new ConfigColumnMeta(39, "critRatio5", "INT"),
        new ConfigColumnMeta(40, "effectHit5", "INT"),
        new ConfigColumnMeta(41, "effectDodge5", "INT"),
        new ConfigColumnMeta(42, "maxHP6", "INT"),
        new ConfigColumnMeta(43, "attack6", "INT"),
        new ConfigColumnMeta(44, "defence6", "INT"),
        new ConfigColumnMeta(45, "speed6", "INT"),
        new ConfigColumnMeta(46, "crit6", "INT"),
        new ConfigColumnMeta(47, "critRatio6", "INT"),
        new ConfigColumnMeta(48, "effectHit6", "INT"),
        new ConfigColumnMeta(49, "effectDodge6", "INT"),
        new ConfigColumnMeta(50, "maxHP7", "INT"),
        new ConfigColumnMeta(51, "attack7", "INT"),
        new ConfigColumnMeta(52, "defence7", "INT"),
        new ConfigColumnMeta(53, "speed7", "INT"),
        new ConfigColumnMeta(54, "crit7", "INT"),
        new ConfigColumnMeta(55, "critRatio7", "INT"),
        new ConfigColumnMeta(56, "effectHit7", "INT"),
        new ConfigColumnMeta(57, "effectDodge7", "INT"),
        new ConfigColumnMeta(58, "maxHP8", "INT"),
        new ConfigColumnMeta(59, "attack8", "INT"),
        new ConfigColumnMeta(60, "defence8", "INT"),
        new ConfigColumnMeta(61, "speed8", "INT"),
        new ConfigColumnMeta(62, "crit8", "INT"),
        new ConfigColumnMeta(63, "critRatio8", "INT"),
        new ConfigColumnMeta(64, "effectHit8", "INT"),
        new ConfigColumnMeta(65, "effectDodge8", "INT"),
        new ConfigColumnMeta(66, "maxHP9", "INT"),
        new ConfigColumnMeta(67, "attack9", "INT"),
        new ConfigColumnMeta(68, "defence9", "INT"),
        new ConfigColumnMeta(69, "speed9", "INT"),
        new ConfigColumnMeta(70, "crit9", "INT"),
        new ConfigColumnMeta(71, "critRatio9", "INT"),
        new ConfigColumnMeta(72, "effectHit9", "INT"),
        new ConfigColumnMeta(73, "effectDodge9", "INT"),
        new ConfigColumnMeta(74, "maxHP10", "INT"),
        new ConfigColumnMeta(75, "attack10", "INT"),
        new ConfigColumnMeta(76, "defence10", "INT"),
        new ConfigColumnMeta(77, "speed10", "INT"),
        new ConfigColumnMeta(78, "crit10", "INT"),
        new ConfigColumnMeta(79, "critRatio10", "INT"),
        new ConfigColumnMeta(80, "effectHit10", "INT"),
        new ConfigColumnMeta(81, "effectDodge10", "INT"),
        new ConfigColumnMeta(82, "spCoe", "LIST<INT>"),
        new ConfigColumnMeta(83, "spCoe2", "INT"),
        new ConfigColumnMeta(84, "spCoe3", "INT"),
        new ConfigColumnMeta(85, "spCoe4", "INT"),
        new ConfigColumnMeta(86, "spCoe5", "INT"),
        new ConfigColumnMeta(87, "spCoe6", "INT"),
        new ConfigColumnMeta(88, "spCoe7", "INT"),
        new ConfigColumnMeta(89, "spCoe8", "INT"),
        new ConfigColumnMeta(90, "spCoe9", "INT"),
        new ConfigColumnMeta(91, "spCoe10", "INT"));
  }
}
