syntax = "proto3";
option java_package = "ly.proto";

// 服务器间通信协议负载消息的类型
enum ServerMsgType
{
  protobufMsg = 0; // protobuf  消息
  structMsg = 1; //bean 结构体消息
}

// 服务器间通信协议
message csServer2Server
{
  ServerMsgType  type = 1;
  int32 cmd = 2;    //protobufMsg 则为 消息号 ；  structMsg 则为 结构体定义的枚举号
  bytes data = 3;
}

// 服务器间通信协议
message scServer2Server
{
  ServerMsgType  type = 1;
  int32 cmd = 2;    //protobufMsg 则为 消息号 ；  structMsg 则为 结构体定义的枚举号
  bytes data = 3;
}

// 心跳包
message csRpcPing
{
  int64 time = 1;
  string serverId = 2;
}

message scRpcPing
{
  int64 time = 1;
}

// 网关调用游戏服务器Rpc方法
message csGate2GameRpcGameCall{
  int32 cmd = 1;// client 发送给gate 请求 cmd
  int32 sid = 2;// client 发送给gate 请求 会话id
  int64 guid = 3;// client 发送给gate 请求 玩家id
  int32 seq = 4;// client 发送给gate 请求 序列id
  bytes data = 5;// client 发送给gate 请求 数据
}
// 网关调用游戏服务器Rpc方法响应
message scGate2GameRpcGameCall{
  int32 cmd = 1;// game 发送给gate 的客户端下行 cmd
  int32 sid = 2;// game 发送给gate 的客户端会话id
  int32 seq = 3;// game 发送给gate 的客户端下行序列id
  bytes data = 4;// game 发送给gate 响应 数据
}
